# Generated by Django 5.2.5 on 2025-09-04 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('section', models.CharField(help_text='e.g., A, B, C', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Maximum number of students allowed')),
                ('description', models.TextField(blank=True, help_text='Optional notes about the section', null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='campus.campus')),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Assign a class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacherrole')),
            ],
            options={
                'verbose_name': 'Class / Section',
                'verbose_name_plural': 'Classes / Sections',
                'ordering': ['name', 'section'],
                'unique_together': {('name', 'section', 'campus')},
            },
        ),
    ]
