# Generated by Django 5.2.5 on 2025-09-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Class/Grade name e.g. Grade 3, O-Level', max_length=50)),
                ('section', models.CharField(help_text='Section name e.g. A, B, C', max_length=20)),
                ('category', models.CharField(choices=[('Regular', 'Regular'), ('Prep', 'Prep'), ('Montessori', 'Montessori'), ('Other', 'Other')], default='Regular', help_text='Type of class (Regular, Prep, Montessori, etc.)', max_length=50)),
                ('is_combined', models.BooleanField(default=False, help_text='Is this a combined class?')),
                ('combined_with', models.CharField(blank=True, help_text='If combined, mention with which grade e.g. Class 5', max_length=50, null=True)),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Maximum number of students allowed')),
                ('enrolled_students', models.PositiveIntegerField(default=0, help_text='Current enrolled students')),
                ('total_boys', models.PositiveIntegerField(default=0, help_text='Number of boys in this class')),
                ('total_girls', models.PositiveIntegerField(default=0, help_text='Number of girls in this class')),
                ('avg_class_size', models.PositiveIntegerField(default=0, help_text='Average number of students in this section')),
                ('subjects', models.TextField(blank=True, help_text='Comma separated list of subjects offered in this class', null=True)),
                ('medium_of_instruction', models.CharField(choices=[('English', 'English'), ('Urdu', 'Urdu'), ('Bilingual', 'Bilingual')], default='English', max_length=50)),
                ('academic_year_start', models.DateField(blank=True, null=True)),
                ('academic_year_end', models.DateField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Temporary Closed', 'Temporary Closed')], default='Active', max_length=20)),
                ('governing_body', models.CharField(blank=True, help_text='e.g. Matric, Cambridge, IB', max_length=100, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional notes about the section', null=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='campus.campus')),
                ('class_teacher', models.ForeignKey(blank=True, help_text='Assign a class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacherrole')),
            ],
            options={
                'verbose_name': 'Class / Section',
                'verbose_name_plural': 'Classes / Sections',
                'ordering': ['name', 'section'],
                'unique_together': {('name', 'section', 'campus')},
            },
        ),
    ]
