# Generated by Django 5.2.5 on 2025-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='academic_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_year_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='enrolled_students',
            field=models.PositiveIntegerField(default=0, help_text='Current enrolled students'),
        ),
        migrations.AddField(
            model_name='grade',
            name='governing_body',
            field=models.CharField(blank=True, help_text='e.g. Matric, Cambridge, IB', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='medium_of_instruction',
            field=models.CharField(choices=[('English', 'English'), ('Urdu', 'Urdu'), ('Bilingual', 'Bilingual')], default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='grade',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Temporary Closed', 'Temporary Closed')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='grade',
            name='subjects',
            field=models.TextField(blank=True, help_text='Comma separated list of subjects offered in this class', null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='total_boys',
            field=models.PositiveIntegerField(default=0, help_text='Number of boys in this class'),
        ),
        migrations.AddField(
            model_name='grade',
            name='total_girls',
            field=models.PositiveIntegerField(default=0, help_text='Number of girls in this class'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(help_text='Class/Grade name e.g. Grade 3, O-Level', max_length=50),
        ),
        migrations.AlterField(
            model_name='grade',
            name='section',
            field=models.CharField(help_text='Section name e.g. A, B, C', max_length=20),
        ),
    ]
