# Generated by Django 5.2.5 on 2025-09-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('classes_section', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='grade',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='campus.campus')),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='teachers.teacher')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='classes_section.grade')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='classes_section.section')),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='academic_year_end',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='academic_year_start',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='avg_class_size',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='category',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='class_teacher',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='combined_with',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='description',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='enrolled_students',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='governing_body',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='is_combined',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='medium_of_instruction',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='section',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='total_boys',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='total_girls',
        ),
    ]
