# Generated by Django 5.2.5 on 2025-09-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_section', '0002_grade_academic_year_end_grade_academic_year_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='avg_class_size',
            field=models.PositiveIntegerField(default=0, help_text='Average number of students in this section'),
        ),
        migrations.AddField(
            model_name='grade',
            name='category',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Prep', 'Prep'), ('Montessori', 'Montessori'), ('Other', 'Other')], default='Regular', help_text='Type of class (Regular, Prep, Montessori, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='grade',
            name='combined_with',
            field=models.CharField(blank=True, help_text='If combined, mention with which grade e.g. Class 5', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='is_combined',
            field=models.BooleanField(default=False, help_text='Is this a combined class?'),
        ),
    ]
