# Generated by Django 5.2.5 on 2025-09-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_section', '0002_alter_grade_options_alter_grade_unique_together_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Select students from this grade to assign to this section', related_name='sections', to='students.student'),
        ),
    ]
