# Generated by Django 5.2.5 on 2025-09-22 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesheet_attendancerecord_delete_attendance'),
        ('campus', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesheet',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesheet',
            name='class_name',
            field=models.CharField(default='Default Class', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendancesheet',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
        migrations.CreateModel(
            name='AttendanceCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Present'), ('L', 'Late'), ('E', 'Excused absence'), ('U', 'Unexcused absence')], max_length=1)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='attendance.attendancesheet')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_cells', to='students.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_cells', to='teachers.teacher')),
            ],
            options={
                'unique_together': {('sheet', 'student', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
