// Mock data - replace with actual API calls
export const dashboardData = {
  students: 100,
  teachers: 10,
  campuses: 5,
  grades: 15,
}

export const mockStudents = [
  {
    id: 1,
    name: "Ahmed Ali",
    grNo: "ST001",
    grade: "Grade 10",
    section: "A",
    campus: "Main Campus",
    status: "active",
    phone: "+92-300-1234567",
    fatherName: "Ali Ahmed",
    email: "ahmed.ali@student.edu",
    address: "123 Student Street, Karachi",
    dateOfBirth: "2008-05-15",
    admissionDate: "2023-08-01",
  },
  {
    id: 2,
    name: "Fatima Khan",
    grNo: "ST002",
    grade: "Grade 9",
    section: "B",
    campus: "North Campus",
    status: "active",
    phone: "+92-301-2345678",
    fatherName: "Khan Sahib",
    email: "fatima.khan@student.edu",
    address: "456 Learning Avenue, Lahore",
    dateOfBirth: "2009-03-22",
    admissionDate: "2023-08-01",
  },
  {
    id: 3,
    name: "Hassan Ali",
    grNo: "ST003",
    grade: "Grade 11",
    section: "A",
    campus: "Main Campus",
    status: "active",
    phone: "+92-302-3456789",
    fatherName: "Ali Hassan",
    email: "hassan.ali@student.edu",
    address: "789 Education Road, Karachi",
    dateOfBirth: "2007-11-08",
    admissionDate: "2022-08-01",
  },
]

export const mockTeachers = [
  {
    id: 1,
    name: "Dr. Sarah Wilson",
    email: "sarah.wilson@school.edu",
    contact: "+92-302-3456789",
    subjects: "Mathematics, Physics",
    campus: "Main Campus",
    experience: "8 years",
    qualification: "PhD in Mathematics",
    joiningDate: "2016-09-01",
    address: "321 Faculty Street, Karachi",
  },
  {
    id: 2,
    name: "Prof. Muhammad Hassan",
    email: "m.hassan@school.edu",
    contact: "+92-303-4567890",
    subjects: "English, Literature",
    campus: "North Campus",
    experience: "12 years",
    qualification: "Masters in English Literature",
    joiningDate: "2012-08-15",
    address: "654 Teacher Avenue, Lahore",
  },
  {
    id: 3,
    name: "Ms. Ayesha Ahmed",
    email: "ayesha.ahmed@school.edu",
    contact: "+92-304-5678901",
    subjects: "Chemistry, Biology",
    campus: "Main Campus",
    experience: "5 years",
    qualification: "Masters in Chemistry",
    joiningDate: "2019-01-10",
    address: "987 Science Lane, Karachi",
  },
]

export const mockCampuses = [
  {
    id: 1,
    name: "Main Campus",
    code: "MC001",
    address: "123 Education Street, Karachi",
    capacity: 500,
    currentStudents: 450,
    status: "active",
    facilities: "Library, Science Labs, Computer Lab, Sports Ground",
    principal: "Dr. Ahmed Khan",
    establishedYear: "1995",
    contactNumber: "+92-21-1234567",
  },
  {
    id: 2,
    name: "North Campus",
    code: "NC002",
    address: "456 Learning Avenue, Lahore",
    capacity: 300,
    currentStudents: 280,
    status: "active",
    facilities: "Sports Ground, Art Studio, Music Room",
    principal: "Prof. Fatima Ali",
    establishedYear: "2005",
    contactNumber: "+92-42-2345678",
  },
  {
    id: 3,
    name: "South Campus",
    code: "SC003",
    address: "789 Knowledge Road, Islamabad",
    capacity: 400,
    currentStudents: 350,
    status: "active",
    facilities: "Library, Computer Lab, Auditorium",
    principal: "Dr. Hassan Ahmed",
    establishedYear: "2010",
    contactNumber: "+92-51-3456789",
  },
]

export const mockGrades = [
  {
    id: 1,
    name: "Grade 10",
    section: "A",
    campus: "Main Campus",
    classTeacher: "Dr. Sarah Wilson",
    capacity: 30,
    currentStudents: 28,
    subjects: "Mathematics, Physics, Chemistry, English, Urdu",
    classRoom: "Room 101",
  },
  {
    id: 2,
    name: "Grade 9",
    section: "B",
    campus: "North Campus",
    classTeacher: "Prof. Muhammad Hassan",
    capacity: 25,
    currentStudents: 24,
    subjects: "English, Literature, History, Geography, Urdu",
    classRoom: "Room 205",
  },
  {
    id: 3,
    name: "Grade 11",
    section: "A",
    campus: "Main Campus",
    classTeacher: "Ms. Ayesha Ahmed",
    capacity: 32,
    currentStudents: 30,
    subjects: "Chemistry, Biology, Physics, Mathematics, English",
    classRoom: "Room 301",
  },
]
