# Generated by Django 5.2.5 on 2025-09-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_id', models.CharField(help_text='Format: CITY-YEAR-POSTAL-NO (e.g., KHI-16-75080-01)', max_length=50)),
                ('campus_code', models.CharField(max_length=50)),
                ('campus_name', models.CharField(max_length=255)),
                ('campus_type', models.CharField(choices=[('main', 'Main'), ('branch', 'Branch')], default='main', max_length=20)),
                ('governing_body', models.CharField(blank=True, max_length=255, null=True)),
                ('accreditation', models.CharField(blank=True, max_length=255, null=True)),
                ('languages_of_instruction', models.CharField(help_text='e.g. English, Urdu', max_length=255)),
                ('academic_year_start', models.DateField()),
                ('academic_year_end', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('province_state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('official_email', models.EmailField(max_length=254)),
                ('head_name', models.CharField(help_text='Principal / Director name', max_length=255)),
                ('head_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('head_coordinator_name', models.CharField(blank=True, max_length=255, null=True)),
                ('head_coordinator_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('total_staff_members', models.PositiveIntegerField(default=0)),
                ('total_teachers', models.PositiveIntegerField(default=0)),
                ('total_coordinators', models.PositiveIntegerField(default=0)),
                ('total_maids', models.PositiveIntegerField(default=0)),
                ('total_guards', models.PositiveIntegerField(default=0)),
                ('other_staff', models.PositiveIntegerField(default=0)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('shift_available', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('both', 'Both')], default='morning', max_length=20)),
                ('education_levels', models.TextField(blank=True, help_text='Comma-separated education levels e.g. Primary, Secondary, College, IT Courses')),
                ('student_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('under_construction', 'Under Construction')], default='active', max_length=20)),
                ('num_rooms', models.PositiveIntegerField(default=0)),
                ('total_classrooms', models.PositiveIntegerField(default=0)),
                ('avg_class_size', models.PositiveIntegerField(default=0)),
                ('current_class_size', models.PositiveIntegerField(default=0)),
                ('num_computer_labs', models.PositiveIntegerField(default=0)),
                ('num_science_labs', models.PositiveIntegerField(default=0)),
                ('num_language_labs', models.PositiveIntegerField(default=0)),
                ('library_available', models.BooleanField(default=False)),
                ('sports_facilities', models.BooleanField(default=False)),
                ('transport_facility', models.BooleanField(default=False)),
                ('canteen_available', models.BooleanField(default=False)),
                ('meals_available', models.BooleanField(default=False)),
                ('num_toilets', models.PositiveIntegerField(default=0)),
                ('toilets_male', models.PositiveIntegerField(default=0)),
                ('toilets_female', models.PositiveIntegerField(default=0)),
                ('toilets_accessible', models.PositiveIntegerField(default=0)),
                ('toilets_teachers', models.PositiveIntegerField(default=0)),
                ('facilities', models.TextField(blank=True, null=True)),
                ('other_facilities', models.TextField(blank=True, help_text='Extra facilities in plain text (comma separated or free text)', null=True)),
                ('power_backup', models.BooleanField(default=False)),
                ('internet_wifi', models.BooleanField(default=False)),
                ('is_draft', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
