# Generated by Django 5.2.5 on 2025-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus',
            name='science_labs',
        ),
        migrations.AddField(
            model_name='campus',
            name='biology_labs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='chemistry_labs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_students_female',
            field=models.PositiveIntegerField(default=0, help_text='Number of female students'),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_students_male',
            field=models.PositiveIntegerField(default=0, help_text='Number of male students'),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_teachers_female',
            field=models.PositiveIntegerField(default=0, help_text='Number of female teachers'),
        ),
        migrations.AddField(
            model_name='campus',
            name='num_teachers_male',
            field=models.PositiveIntegerField(default=0, help_text='Number of male teachers'),
        ),
        migrations.AddField(
            model_name='campus',
            name='office_rooms',
            field=models.PositiveIntegerField(default=0, help_text='Number of office rooms'),
        ),
        migrations.AddField(
            model_name='campus',
            name='physics_labs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campus',
            name='special_classes',
            field=models.CharField(blank=True, help_text='Special classes like Montessori, Prep Section', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='campus',
            name='toilets_teachers',
            field=models.PositiveIntegerField(default=0, help_text='Number of toilets reserved for teachers'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='num_students',
            field=models.PositiveIntegerField(default=0, help_text='Total students'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='num_teachers',
            field=models.PositiveIntegerField(default=0, help_text='Total teachers'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='registration_no',
            field=models.CharField(blank=True, help_text='Official campus registration or license number', max_length=100, null=True),
        ),
    ]
