# Generated by Django 5.2.5 on 2025-09-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_remove_campus_science_labs_campus_biology_labs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
